config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  delete '/sessions' => 'sessions#destroy'
  get   '/sessions/new'  => 'sessions#new'
  post   '/sessions'  => 'sessions#create'
  get '/nearby_musicians' => 'musicians#nearby_musicians'
  get '/musicians/show_me' => "musicians#show_me"

  root 'welcome#index'

  resources :musicians

  post '/musicians/set_location' => 'musicians#set_location'

end

app/models/musician.rb
class Musician < ActiveRecord::Base
  has_secure_password
  validates :username, :email, :location, :instrument, :skill_level, presence: true
  validates :email, :username, uniqueness: true
end

app/models/we_jam_seeder.rb
require 'faker'

class WeJamSeeder
  def seed!
    purge_database_of!([Musician])
    seed_musicians
  end

  private

    def purge_database_of!(models)
      models.each{ |m| puts "Destroying all #{m}"; m.destroy_all }
    end

    def seed_musicians
      puts "Creating seed Musicians"
      Musician.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, location: "Oakland", instrument: Faker::Lorem.word, genre: Faker::Lorem.word, skill_level: Faker::Lorem.word, url: Faker::Internet.url, gravatar_url: Faker::Internet.url, notes: Faker::Lorem.sentence, available: [false, true].sample, lat: 37.789307, long:-122.425223)
      Musician.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, location: "Oakland", instrument: Faker::Lorem.word, genre: Faker::Lorem.word, skill_level: Faker::Lorem.word, url: Faker::Internet.url, gravatar_url: Faker::Internet.url, notes: Faker::Lorem.sentence, available: [false, true].sample, lat: 37.781270, long:-122.421450)
      Musician.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, location: "Oakland", instrument: Faker::Lorem.word, genre: Faker::Lorem.word, skill_level: Faker::Lorem.word, url: Faker::Internet.url, gravatar_url: Faker::Internet.url, notes: Faker::Lorem.sentence, available: [false, true].sample, lat: 37.793946, long:-122.396059)
      Musician.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, location: "Oakland", instrument: Faker::Lorem.word, genre: Faker::Lorem.word, skill_level: Faker::Lorem.word, url: Faker::Internet.url, gravatar_url: Faker::Internet.url, notes: Faker::Lorem.sentence, available: [false, true].sample, lat: 37.789933, long:-122.394307)
      Musician.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, location: "Oakland", instrument: Faker::Lorem.word, genre: Faker::Lorem.word, skill_level: Faker::Lorem.word, url: Faker::Internet.url, gravatar_url: Faker::Internet.url, notes: Faker::Lorem.sentence, available: [false, true].sample, lat: 37.793123, long:-122.403101)
      Musician.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, location: "Oakland", instrument: Faker::Lorem.word, genre: Faker::Lorem.word, skill_level: Faker::Lorem.word, url: Faker::Internet.url, gravatar_url: Faker::Internet.url, notes: Faker::Lorem.sentence, available: [false, true].sample, lat: 37.752177, long:-122.484237)
      Musician.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, location: "Oakland", instrument: Faker::Lorem.word, genre: Faker::Lorem.word, skill_level: Faker::Lorem.word, url: Faker::Internet.url, gravatar_url: Faker::Internet.url, notes: Faker::Lorem.sentence, available: [false, true].sample, lat: 37.769436, long:-122.406248)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController
  def index
    if session[:musician_id] 
      musicians_path
    else
      redirect_to :root
    end
  end
	
  def show_me
    @musician = Musician.find(session[:musician_id])
    render :json => @musician
  end 

	def new
    # Creation of new musician is necessary for our sign-up form to work
		@musician = Musician.new
	end

  def create
    @musician = Musician.new(musician_params)
    if @musician.save
      session[:musician_id] = @musician.id
      redirect_to musicians_path
    else
      render :text => @musician.errors.full_messages.join(', '), :status => :unprocessable_entity
    end
  end

  def show
    @musician = Musician.find(params[:id])
    render :partial => "show", :locals => {:musician => @musician}
  end

	def nearby_musicians
		@musicians = Musician.all 
		render :json => @musicians
	end 
	
  def set_location
    @musician = Musician.find_by(id: session[:musician_id])
    if @musician.update_attributes(lat: params[:lat], long: params[:long])
      # ajax response: pass back nearby musician objects
      redirect_to musicians_path
    else
      render :text => @musician.errors.full_messages.join(', '), :status => :unprocessable_entity
    end   
  end

  def edit
    @musician = Musician.find(params[:id])
    render :partial => "edit_form", :locals => {:musician => @musician}
  end

  def update
    @musician = Musician.find(params[:id])
    if @musician.update_attributes(musician_params)
      redirect_to musicians_path
    else
      render :text => @musician.errors.full_messages.join(', '), :status => :unprocessable_entity
    end 	
  end

 private

  def musician_params
    params.require(:musician).permit(:username, :email, :password, :location, :instrument, :genre, :skill_level, :url, :gravatar_url, :availability, :notes, :lat, :long)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
  def new
    render 'new'
  end

  def create
    musician = Musician.find_by_email(params[:email])
    if musician && musician.authenticate(params[:password])
      session[:musician_id] = musician.id
      redirect_to musicians_path
    else
      redirect_to :root
    end
  end

  def destroy
    reset_session
    redirect_to :root
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
    @musician = Musician.new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musicians_helper.rb
module MusiciansHelper
  def viewing_my_own_profile
    Musician.find_by(id: session[:musician_id])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <% content_for :title do %> WeJam <% end %>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?sensor=false" %>
    <script src="http://www.myersdaily.org/joseph/javascript/md5.js"></script>
    <%= csrf_meta_tags %>
</head>

<body>
  <div class="sticky">
    <nav class="top-bar" data-topbar role="navigation">
      <section class="top-bar-section">
        <ul class-"title-area">
          <li class="name">
            <h1 id="logo">WeJam</h1>
          </li>
        </ul>
        <ul class="right">
          <li>
            <% if viewing_my_own_profile %>
              <%= link_to 'Log out', sessions_path, method: :delete %>
            <% end %>
          </li>
        </ul>
        <ul class="right">
          <li>
            <% if viewing_my_own_profile %>
            <%= link_to 'Edit Profile', edit_musician_path(viewing_my_own_profile), method: :get %>
      <% end %>
          </li>
        </ul>
      </section>
    </nav>
  </div>

  <%= yield %>
  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/musicians/_edit_form.html.erb
<div class="forms_container">
<div data-reveal=" ">
  <h2 class="profile_form">Edit Profile</h2>
  <div class="errors"></div>
  <div class="row">
    <div class="small-5 columns">
      <%= form_for @musician do |f|%>
      <p>
        <label for="left-label" class="left">Musician Name</label>
        <%= f.text_field :username %>
      </p>
      <p>
        <label for="left-label" class="left">Email</label>
        <%= f.text_field :email %>
      </p>
      <p>
        <label for="left-label" class="left">Password</label>
        <%= f.password_field :password %>
      </p>
      <p>
        <label for="left-label" class="left">Location</label>
        <%= f.text_field :location %>
      </p>
      <p>
        <label for="left-label" class="left">Instrument</label>
        <%= f.text_field :instrument %>
      </p>
    </div>
    <div class="small-5 columns">
      <p>
        <label for="left-label" class="left">Genre</label>
        <%= f.text_field :genre %>
      </p>
      <p>
         <label for="left-label" class="left">Skill Level</label>
        <%= f.text_field :skill_level %>
      </p>
      <p>
        <label for="left-label" class="left">Link Your Sound Clips</label>
        <%= f.text_field :url %>
      </p>
      <p>
        <label for="left-label" class="left">Describe Your Jam Style</label>
        <%= f.text_area :notes %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="small-4  small-offset-4 end columns">
    <p><%= submit_tag "Edit Your Profile",  :class=>"button postfix" %></p>
    </div>
  </div>
  <% end %>
</div>

app/views/musicians/_new.html.erb
<div data-reveal=" ">
  <h2 class="sign-up">Play with someone</h2>
  <div class="row">
    <div class="small-5 columns">
      <%= form_for @musician do |f|%>
      <p>
        <label for="left-label" class="left">Musician Name</label>
        <%= f.text_field :username %>
      </p>
      <p>
        <label for="left-label" class="left">Email</label>
        <%= f.text_field :email %>
      </p>
      <p>
        <label for="left-label" class="left">Password</label>
        <%= f.password_field :password %>
      </p>
      <p>
        <label for="left-label" class="left">Location</label>
        <%= f.text_field :location %>
      </p>
      <p>
        <label for="left-label" class="left">Instrument</label>
        <%= f.text_field :instrument %>
      </p>
    </div>
    <div class="small-5 columns">
      <p>
        <label for="left-label" class="left">Genre</label>
        <%= f.text_field :genre %>
      </p>
      <p>
         <label for="left-label" class="left">Skill Level</label>
        <%= f.text_field :skill_level %>
      </p>
      <p>
        <label for="left-label" class="left">Link Your Sound Clips</label>
        <%= f.text_field :url %>
      </p>
      <p>
        <label for="left-label" class="left">Describe Your Jam Style</label>
        <%= f.text_area :notes %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="small-4  small-offset-4 end columns">
      <p>
        <%= submit_tag "Jam With Us!",  :class=>"button postfix" %>
      </p>
    </div>
  </div>
  <% end %>
  <a class="closing close-reveal-modal">×</a>
</div>

app/views/musicians/_show.html.erb
<div class="show_container">

  <h1><%= @musician.username %></h1>
 
  <p>Location: <%= @musician.location %></p>
  <p>Instrument: <%= @musician.instrument %></p>
  <p>Genre: <%= @musician.genre %></p>
  <p>Skill Level: <%= @musician.skill_level %></p>
  <p>Soundcloud/YouTube Link: <a href="<%= @musician.url%>"><%= @musician.url %></a></p>
  <p>About Me: <%= @musician.notes %></p>

  <p> <a href="mailto:<%= @musician.email %>">Email Me!</a></p>

     
  <% if viewing_my_own_profile != nil %>
    <%= link_to 'edit', edit_musician_path(@musician) %>
  <% end %>


</div>

   

app/views/musicians/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>WeJam</title>
	<link rel="stylesheet" src="./stylesheets/weJam.css">
	<script type="text/javascript" src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
	<script type="text/javascript" src="http://code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script>
	<script src="http://code.jquery.com/jquery-latest.js"></script>
	<script src="http://jquery-ui.googlecode.com/svn/tags/latest/ui/jquery.effects.core.js"></script>
	<script src="http://jquery-ui.googlecode.com/svn/tags/latest/ui/jquery.effects.slide.js"></script>
</head>
<body>
	<div class="container">
		<div id="map-canvas">
		</div>
		<div class="sidebar">
		</div>
	</div>
</body>
</html> 

app/views/musicians/show.html.erb
<div class="show_container">

  <h1><%= @musician.username %></h1>
 
  <p>Location: <%= @musician.location %></p>
  <p>Instrument: <%= @musician.instrument %></p>
  <p>Genre: <%= @musician.genre %></p>
  <p>Skill Level: <%= @musician.skill_level %></p>
  <p>Soundcloud/YouTube Link: <a href="<%= @musician.url%>"><%= @musician.url %></a></p>
  <p>Pic Link:  <a href="<%= @musician.gravatar_url%>"><%= @musician.gravatar_url %></a></p>
  <p>About Me: <%= @musician.notes %></p>

  <p> <a href="mailto:<%= @musician.email %>">Email Me!</a></p>

     
  <% if current_musician != nil %>
    <%= link_to 'edit', edit_musician_path(@musician) %>
  <% end %>


</div>

   

app/views/welcome/index.html.erb
<div class="container body-img">
  <div class="row">
    <div id="we-jam-welcome-slogan" class="small-4 columns end phrase-margin">
     Stop Playing With Yourself.
   </div>
 </div>
 <div class="row center">
  <div class="small-4 columns button-margin">
    <div class="button">
      <%= link_to "Sign up ", "#", class: "sign_up white-button", data: { 'reveal-id' => 'newModal'} %>
      <%= content_tag :div, id: 'newModal', class: ['reveal-modal'], data: {reveal: ''} do %>
      <%= render 'musicians/new' %>
      <% end %>
    </div>
    <div class="button">
     <%= link_to "Log In", "#", class: "log_in white-button", data: { 'reveal-id' => 'logModal'} %>
     <%= content_tag :div, id: 'logModal', class: ['reveal-modal'], data: {reveal: ''} do %>
     <%= render '/sessions/new' %>
     <% end %>
   </div>
 </div>
</div>	